swipe:
  3:
    left:
      #command: 'xdotool key alt+Right' # History forward
      sendkey: "LEFTALT+RIGHT"
    right:
      #command: 'xdotool key alt+Left' # History back
      sendkey: "LEFTALT+LEFT"
    up:
      #command: 'xdotool key ctrl+t' # Open new tab
      sendkey: "LEFTCTRL+T"
      keypress:
        LEFTSHIFT:
          #command: 'xdotool key --clearmodifiers ctrl+shift+t' # Open last closed tab
          sendkey: "LEFTCTRL+LEFTSHIFT+T"
    down:
      #command: 'xdotool key ctrl+w' # Close tab
      sendkey: "LEFTCTRL+W"
      keypress:
        LEFTSHIFT:
          #command: 'xdotool key --clearmodifiers ctrl+shift+t' # Open last closed tab
          sendkey: "LEFTCTRL+LEFTSHIFT+T"
  4:
    left:
      workspace: 'next' # Switch to next workspace
      keypress:
        LEFTSHIFT:
          #command: 'xdotool key --clearmodifiers ctrl+alt+shift+Right' # Move window to right side
          sendkey: "LEFTCTRL+LEFTALT+LEFTSHIFT+RIGHT"
    right:
      workspace: 'prev' # Switch to previous workspace
      keypress:
        LEFTSHIFT:
          #command: 'xdotool key --clearmodifiers ctrl+alt+shift+Left' # Move window to left side
          sendkey: "LEFTCTRL+LEFTALT+LEFTSHIFT+LEFT"
    up:
      #command: 'xdotool key Control_L+F10' # Workspace overview
      sendkey: "LEFTCTRL+F10"
      keypress:
        LEFTSHIFT:
          #command: 'xdotool key --clearmodifiers Control_L+F8' # All workspace overview
          sendkey: "LEFTCTRL+F8"
        LEFTMETA:
          window:
            maximized: 'toggle' # Toggle Maximize/Unmaximize Window
    down:
      #command: 'xdotool key Super_L' #aaaaa
      sendkey: "LEFT"

# pinch:
#   2:
#     in:
#       command: 'xdotool keydown ctrl click 4 keyup ctrl' # Zoom in
#     out:
#       command: 'xdotool keydown ctrl click 5 keyup ctrl' # Zoom out
#   4:
#     in:
#       command: 'xdotool key ctrl+F9' # Window overview
#     out:
#       command: 'xdotool key ctrl+F9' # Workspace overview

rotate:
  3:
    clockwise:
      #command: 'xdotool key XF86MonBrightnessUp' # Brightness up
      sendkey: "BRIGHTNESSUP"
    counterclockwise:
      #command: 'xdotool key XF86MonBrightnessDown' # Brightness down
      sendkey: "BRIGHTNESSDOWN"

plugin:
  inputs:
    libinput_command_input: # options for lib/plugin/inputs/libinput_command_input
      enable-tap: true # click to tap
      enable-dwt: true # disable tap while typing
      show-keycodes: true # https://github.com/iberianpig/fusuma-plugin-keypress#add-show-keycode-option
